import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LangProvider } from "@/components/hooks/useLang";
import { ThemeProvider } from "@/components/shared/Theme-provider";
import UserSessionProvider from "@/components/hooks/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


    <html lang="en">
      <body className={inter.className}>
        <UserSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LangProvider>
              {children}
            </LangProvider>
          </ThemeProvider>
        </UserSessionProvider>
      </body>
    </html>


  );
}
